/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-sonik
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SONIK_API_H
#define INCLUDED_SONIK_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_sonik_EXPORTS
#define SONIK_API __GR_ATTR_EXPORT
#else
#define SONIK_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SONIK_API_H */
